site_name: Teknoir Notebook TechDocs
site_description: Operating guide for the Teknoir Notebook App

nav:
  - Overview: index.md
  - Notebook App: notebook-app.md
  - Notebook HelmChart: notebook-helm.md
  - Notebook Image: notebook-image.md

plugins:
  - techdocs-core
