---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: {{ .Release.Namespace }}
  labels:
    app: notebook
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http-notebook
      port: 8888
      targetPort: 8888
      protocol: TCP
      {{- if .Values.nodePort.enabled }}
      nodePort: 31888
      {{- end }}
  selector:
    app: notebook
